In [2]:
import numpy as np
arr=np.arange(1,21)
print("Array:")
print(arr)
print("\nShape:",arr.shape)
print("Maximum:",arr.max())
print("Mininum:",arr.min())
print("Mean:",arr.mean())
print("Standard Deviation:",arr.std())
matrix=arr.reshape(4,5)
print("\n4x5 Matrix:")
print(matrix)
print("\nSecond Row:")
print(matrix[1])
print("\nThied Column:")
print(matrix[:,2])

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Shape: (20,)
Maximum: 20
Mininum: 1
Mean: 10.5
Standard Deviation: 5.766281297335398

4x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Second Row:
[ 6  7  8  9 10]

Thied Column:
[ 3  8 13 18]


In [3]:
import numpy as np
A=np.array([10,20,30,40,50])
B=np.array([5,10,15,20,25])
print("Addition:",A+B)
print("Subtraction:",A-B)
print("Multiplication:",A*B)
print("Division:",A/B)
print("Sum of elements of A:",A.sum())

Addition: [15 30 45 60 75]
Subtraction: [ 5 10 15 20 25]
Multiplication: [  50  200  450  800 1250]
Division: [2. 2. 2. 2. 2.]
Sum of elements of A: 150


In [6]:
import pandas as pd
data={
    "Roll No":[101,102,103,104,105],
    "Name":["Ravi","Priya","Kiran","Anu","Sita"],
    "Marks":[85,92,78,88,95],
}
df=pd.DataFrame(data)
print("DataFrame:")
print(df)
print("\nFirst Three Records:")
print(df.head(3))
print("\nAverage Marks:",df["Marks"].mean())
print("\nHighest Marks Student:")
print(df.loc[df["Marks"].idxmax()])
print("\nLowest Marks Student:")
print(df.loc[df["Marks"].idxmin()])
def grade(mark):
    if mark>=90:
        return "A"
    elif mark>=80:
        return "B"
    else:
        return "C"
df["Grade"]=df["Marks"].apply(grade)
print("\nDataFrame with Grade:")
print(df)

DataFrame:
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95

First Three Records:
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78

Average Marks: 87.6

Highest Marks Student:
Roll No     105
Name       Sita
Marks        95
Name: 4, dtype: object

Lowest Marks Student:
Roll No      103
Name       Kiran
Marks         78
Name: 2, dtype: object

DataFrame with Grade:
   Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A


In [7]:
import pandas as pd
data={
    "Product":["Laptop","Mouse","Keyboerd","Monitor"],
    "Price":[50000,500,1200,10000],
    "Quantity":[10,50,30,15],
}
df=pd.DataFrame(data)
df["Total Value"]=df["Price"]*df["Quantity"]
print(df)
print("\nHighest Total Value Product:")
print(df.loc[df["Total Value"].idxmax()])
print("\nOverall Inventory Value:")
print(df["Total Value"].sum())

    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboerd   1200        30        36000
3   Monitor  10000        15       150000

Highest Total Value Product:
Product        Laptop
Price           50000
Quantity           10
Total Value    500000
Name: 0, dtype: object

Overall Inventory Value:
711000


In [9]:
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["Species"]=pd.Categorical.from_codes(iris.target,iris.target_names)
print("DataFrame:")
print(df)
print("\nFirst Five Rows:")
print(df.head())
print("\nRows and Columns:")
print(df.shape)
print("\nColumn Names:")
print(df.columns)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nSummary Statistics:")
print(df.describe())
print("\nSamples in Each Class:")
print(df["Species"].value_counts())

DataFrame:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       Species  